version: '3.9'

services:
  backend:
    build: ./backend
    container_name: minishop-backend
    ports:
      - "4000:5000" # host:container
    env_file:
      - ./backend/.env
    restart: unless-stopped
